require("dotenv").config();

const {
  SERVER_PORT,
  TELEGRAM_BOT_TOKEN,
  TELEGRAM_BOT_ADMINS,
  PLUSOFON_API_URL,
  PLUSOFON_API_KEY,
  PLUSOFON_CLIENT_ID,
  AMO_TOKEN,
  AMO_URL,
  AMO_INTEGRATION_ID
} = process.env;

if (
  !SERVER_PORT ||
  !TELEGRAM_BOT_TOKEN ||
  !TELEGRAM_BOT_ADMINS ||
  !PLUSOFON_API_URL ||
  !PLUSOFON_API_KEY ||
  !PLUSOFON_CLIENT_ID ||
  !AMO_TOKEN ||
  !AMO_URL ||
  !AMO_INTEGRATION_ID
) {
  console.error("Fill out .env fully.");
  process.exit(1);
}

module.exports = {
  SERVER_PORT,
  TELEGRAM_BOT_TOKEN,
  TELEGRAM_BOT_ADMINS,
  PLUSOFON_API_URL,
  PLUSOFON_API_KEY,
  PLUSOFON_CLIENT_ID,
  AMO_TOKEN,
  AMO_URL,
  AMO_INTEGRATION_ID
};
