require("dotenv").config();

const {
  SERVER_PORT,
  TELEGRAM_BOT_TOKEN,
  TELEGRAM_BOT_ADMINS,
  GOOGLE_SHEET_ID,
  GOOGLE_SHEET_EMAIL,
  GOOGLE_SHEET_PRIVATE_KEY,
  PLUSOFON_API_URL,
  PLUSOFON_API_KEY,
  PLUSOFON_CLIENT_ID,
} = process.env;

if (
  !SERVER_PORT ||
  !TELEGRAM_BOT_TOKEN ||
  !TELEGRAM_BOT_ADMINS ||
  !GOOGLE_SHEET_ID ||
  !GOOGLE_SHEET_EMAIL ||
  !GOOGLE_SHEET_PRIVATE_KEY ||
  !PLUSOFON_API_URL ||
  !PLUSOFON_API_KEY ||
  !PLUSOFON_CLIENT_ID
) {
  console.error("Fill out .env fully.");
  process.exit(1);
}

module.exports = {
  SERVER_PORT,
  TELEGRAM_BOT_TOKEN,
  TELEGRAM_BOT_ADMINS,
  GOOGLE_SHEET_ID,
  GOOGLE_SHEET_EMAIL,
  GOOGLE_SHEET_PRIVATE_KEY,
  PLUSOFON_API_URL,
  PLUSOFON_API_KEY,
  PLUSOFON_CLIENT_ID,
};
